name: Build and Deploy to Vercel

on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.0'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.2.1
      - name: Install dependencies & run scripts
        run: |
          cd modelling
          poetry install
          poetry run python scrape_pbp.py
          poetry run python merge_years.py
          poetry run python compute_end_states.py
          mkdir -p ../frontend/static/data
          cp -r output/output_all_end_prob.json ../frontend/static/data/
          cp -r output/output_all_freq.json ../frontend/static/data/
          cp -r output/meta.json ../frontend/static/data/
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.11.1
      - name: Install frontend
        run: |
          cd frontend
          npm ci
          npm run build
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_TOKEN }}
        run: |
          npm install -g vercel
          vercel --yes --prod --token $VERCEL_TOKEN
